name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.4.2
    - name: Install dependencies
      run: bundle install
    - name: Init credentials
      run: mv spec/environment.ci.rb spec/environment.rb
    - name: Run tests
      run: bundle exec rspec spec
      env:
        AZURE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}
        AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
        AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
